spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/sharding_db?characterEncoding=utf8
    username: root
    password: root
mybatis:
  mapperLocations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true